100-hours-a-week/14-YG-BE

src/main/java/com/moogsan/moongsan_backend/MoongsanBackendApplication.java, src/main/java/com/moogsan/moongsan_backend/domain/BaseEntity.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/Category.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/GroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/GroupBuyCategory.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/Image.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/Role.java
- Group-buy 하위 엔티티 요소들 생성 및 작성
- 생성, 수정, 삭제 시각에 대한 컬럼을 domain 전역에서 상속받을 수 있도록 BaseEntity 작성
- domain/BaseEntity 추가하여 JPA Auditing 기반 생성, 수정, 삭제 컬럼 생성
- domain/groupbuy/entity/Category 작성
- domain/groupbuy/entity/GroupBuy 작성, BaseEntity 상속
- domain/groupbuy/entity/GroupBuyCategory 작성
- domain/groupbuy/entity/Image 작성
- domain/groupbuy/entity/Role 작성
- SpringApplication에 @EnableJpaAuditing 설정하여 Auditing 기능을 전역으로 활성화
-
- 
- [[Sprint #3] BE - 공동구매 상품 관리 기능 개발](https://github.com/100-hours-a-week/14-YG-BE/issues/9)
=> Feature/group-buy/9 manage products, base & group-buy lower level entities added

build.gradle, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/CreateGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/UpdateGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/request/SearchGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/ImageResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyDetail/DetailResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyDetail/UserProfileResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/BasicList/BasicListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/HostedList/HostedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/PagedResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/ParticipantList/ParticipantListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/ParticipantList/ParticipantResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/ParticipatedList/ParticipatedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/wishList/WishListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyUpdate/GroupBuyForUpdateResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/main/GroupBuySummaryResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/main/MainPageResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/main/SectionResponse.java, src/main/java/com/moogsan/moongsan_backend/global/exception/GlobalExceptionHandler.java
CQRS 기반의 DTO 영역 분리, 각 Request, Response Dto 작성
- domain/groupbuy/dto 하위 command, query 디렉토리 생성, 각각 request, response 하위 디렉토리 생성
- 공통 PagedResponse 분리, 제네릭 자료형으로 재사용
- 공통 ImageResponse 분리, BasicList, DetailResponse에서 재사용
- ERD 컬럼명, 코멘트 기반 주석 추가
- build.gradle에서 group명 moogsan에서 moongsan으로 변경
-
-
- [[Sprint #3] BE - 공동구매 상품 관리 기능 개발](https://github.com/100-hours-a-week/14-YG-BE/issues/9)
=> feat(group-buy): add request/response DTOs for product management (#9)

src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UserController.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/response/LoginResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/user/entity/Token.java, src/main/java/com/moogsan/moongsan_backend/domain/user/entity/User.java, src/main/java/com/moogsan/moongsan_backend/domain/user/exception/UnauthorizedException.java, src/main/java/com/moogsan/moongsan_backend/domain/user/repository/TokenRepository.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/LoginService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/SignUpService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/TokenRefreshService.java, src/main/java/com/moogsan/moongsan_backend/global/security/jwt/JwtAuthenticationFilter.java
액세스/리프레시 토큰 쿠키를 통해 전달/재발급
- 로그인 시, 액세스/리프레시 토큰은 쿠키를 통해 전달
- 로그인 시, 닉네임/실명/프로필이미지url은 바디를 통해 전달
- 액세스 토큰 재발행 api 생성 (/api/users/token/refresh)
- 테스트 확인 완료
=> feat/fix(user): 토큰 쿠키로 전달, 토큰 재발행

.gitignore, build.gradle, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/client/AiClient.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyCommandController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/CreateGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/DescriptionGenerationRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/UpdateGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/response/ApiResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/response/DescriptionDto.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java, src/main/java/com/moogsan/moongsan_backend/global/config/WebClientConfig.java, src/main/resources/application.properties
외부 AI 서비스 엔드포인트 설정을 안전하게 관리하기 위해, 운영·스테이징·로컬 환경별 설정 분리 방안 도입
- **프로퍼티 구조 변경**  
- `src/main/resources/application.properties` 에는 공개 설정만 유지
- **외부 설정 파일**  
- 프로젝트 루트 `config/application-secrets.yml` 에 AI 서비스 기본 URL 플레이스홀더 정의  
- `.gitignore` 에 `config/` 폴더 전체 추가
- **디펜던시 및 빈 등록**  
- `spring-boot-starter-webflux` 의존성 추가  
- `WebClientConfig` 클래스로 `WebClient` 빈 등록
- `./gradlew clean build --refresh-dependencies` 로 빌드 및 테스트 통과 확인  
- 로컬 개발 가이드에 외부 설정 파일 생성 방법 문서화
- API 명세서 추가 확인(GROUPBUY:: AI 상품 상세 설명 생성 프록시 v1)
- [[Sprint #3] BE - 공동구매 상품 관리 기능 개발](https://github.com/100-hours-a-week/14-YG-BE/issues/9)
=> feat(group-buy) add AI proxy api, AiClient, WebClient and update gitignore

src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
공동구매 상세 조회 API에 대한 인증 권한을 수정했습니다.
- **Controller 권한 설정 변경**  
- `/api/group-buys/{postId}` 엔드포인트에 인증 없이 접근 가능하도록 허용  
1. 인증 없이 `GET /api/group-buys/{postId}` 호출 시 정상적으로 상세 정보 반환 확인  
2. `./gradlew clean build` 및 기존 테스트 모두 통과 확인
- API 명세서 및 보안 정책 문서에 권한 변경 사항 반영 여부  
- [[Sprint #3] BE - 공동구매 상품 관리 기능 개발](https://github.com/100-hours-a-week/14-YG-BE/issues/9
=> feat(group-buy): allow detail view without permission

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyCommandController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyQueryController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyDetail/DetailResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/BasicList/BasicListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/HostedList/HostedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/ParticipatedList/ParticipatedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/wishList/WishListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/repository/WishRepository.java
전체 공구/관심 공구/주최 공구/참여 공구 리스트 및 게시글 상세 조회에 isWish , isParticipant추가
- 전체 공구/관심 공구/주최 공구/참여 공구 리스트에 isWish mapper 추가
- 게시글 상세 조회에 isWish mapper 추가
- cursor 사용 시 10개씩 조회되는 게시글(최대 10개)에 대한 관심 등록 여부를 조회하는 메서드 추가하여 오버헤드 줄임
- isWish, isParticipant 필드가 아닌 게터에 @JsonProperty 사용
- 빌드 및 빌드 파일로 실행 확인
- Postman 응답 확인 및 교차 검증 완료
- (예정) 주최 공구, 참여 공구에 적절한 커서 사용
- [#10 공동구매 상품 관리 기능 개선 및 확장](https://github.com/100-hours-a-week/14-YG-BE/issues/32)
=> feat(group-buy): isWish 조회 메서드, 컬럼 mapper 추가, JsonProperty 위치 수정

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyQueryController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService.java, src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java, src/main/java/com/moogsan/moongsan_backend/global/security/jwt/JwtAuthenticationFilter.java
Wish 추가 후 메인 리스트 조회, 공동구매 게시글 상세 조회 시 403 에러 발생하여 원인 코드 분석 후 수정
- 메인 리스트, 상세조회 controller 수정
- Wish로 인해 추가된 CustomUserDetails에 Optional 적용
- User가 아닌 Long으로 파라미터 전달. primitive 타입 적용하여 null 허용 강화
- SecurityConfig 수정
- 메인과 상세 조회의 경우 GET requestMatchers로 변경
- JwtAuthenticationFilter 수정
- 공개 엔드포인트이면 토큰 검사 없이 통과하도록 수정
- 빌드 및 빌드 파일로 실행 확인
- Postman 응답 확인 및 교차 검증 완료
- 
- [#10 공동구매 상품 관리 기능 개선 및 확장](https://github.com/100-hours-a-week/14-YG-BE/issues/32)
=> fix(group-buy):  allow unauthenticated access to public endpoint (#10)

src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UserController.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/SignUpService.java
버그 픽스 : 캐시 방지 헤더 추가
- 버그 내용 : 다른 사용자가 페이지를 접속했을 때 이전 사용자 정보가 보이는 문제
- 원인 예상 : 서버 응답이 캐시(nginx, 브라우저)되어 다른 사용자에게 전달되는 버그가 발생
- 해결 방안 : /users/profile 의 내용을 절대 캐싱하지 말 것을 명시함 (response.setHeader())
- build/bootRun 동작 완료
-
=> fix(user): 캐시 방지 헤더 추가

build.gradle, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/GroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/repository/GroupBuyRepository.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService.java, src/main/resources/db/migration/V1__init_schema.sql, src/main/resources/db/migration/V2__insert_dummy_data.sql
- 정책 기반 상태 필드인 `dueSoon`의 값이 실제 정책 기준과 일치하지 않는 문제를 해결했습니다.  
- 이에 따라 `init_schema.sql` 및 `더미 데이터`를 실 엔티티 기준으로 정비하고,  
- 빌드 설정(`build.gradle`)을 Flyway 및 테스트 환경에 맞춰 정리하였습니다.
- `GroupBuyRepository` 내 `findDueSoonOnly()` JPQL 쿼리 유지
- `dueSoon` 값이 정책(`DueSoonPolicy`) 기준과 불일치하는 사례 발견
- 관련 조회 로직 로그 추가 및 정책 적용 여부 확인 로직 점검
- `orders` 테이블 생성 추가
- `deleted_at`, `deleted_count`, `modified_at`, `status` 등 공통 필드 추가
- `GroupBuy`, `Users` 등 주요 테이블 컬럼 순서 및 자료형 재정렬
- 실제 Entity 클래스와의 정합성 유지 목적
- `dueSoon` 테스트를 위한 판매량(`leftAmount`, `totalAmount`) 조정
- 설명(description) 보완 및 상황별 상태 조합 다양화
- 테스트 시 사용자 흐름 검증 및 정책 테스트 가능하도록 구성
- Flyway 의존성 명확히 추가 및 버전 고정
- 테스트/마이그레이션 환경을 고려한 의존성 정리
- 불필요하거나 중복된 의존성 제거로 빌드 속도 및 안정성 개선
- `dueSoon` 필드 접근 방식 점검 (`isDueSoon` vs `getDueSoon`)
- DTO 매핑 시 실제 정책 기준 값이 누락되지 않도록 매퍼 로직 보완
- …
=> fix(schema): build.gradle 수정, ORM 기준 init schema 및 더미 데이터 정비, dueSoon 정책 반영

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/CreateGroupBuyRequest.java
v1에서는 일반 사용자들이 직접 공구글을 작성할 수 없어 관리자가 대신 작성해야 함
이때 주최자의 구매 수량의 최소값을 1에서 0으로 조정하여 관리자가 글 생성 시 불필요한 주문이 등록되는 것을 방지
- GroupBuy Entity에서 hostQuantity 최소값 0으로 조정
-
- 
-
=> feat(group-buy): temporarily change min value of hostQuantity (#10)

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyDetail/UserProfileResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java
모달에서 주최자 실명 필요
- 공구 게시글 상세 조회 UserProfileResponse dto에 name 추가
- UserProfileResponse 매퍼에 name 매핑
-
- 
-
=> feat(group-buy): 게시글 상세 조회 response dto에 주최자 실명 추가(#10)

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/request/CreateGroupBuyRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java, src/main/resources/application.properties
AI 서버 응답 지연 가능성을 고려하여 WebClientConfig의 HttpClient 응답 타임아웃을 2분(120초)으로 수정하고, Spring Boot 내장 서버 및 비동기 요청 타임아웃을 120초로 조정했습니다.
- **WebClientConfig 변경**  
- HttpClient에 `.responseTimeout(Duration.ofSeconds(120))` 설정 추가  
- **application.properties 변경**  
- `server.tomcat.connection-timeout=120s`  
- `spring.mvc.async.request-timeout=120s`
- WebClient 타임아웃 설정이 다른 HTTP 클라이언트 설정과 충돌 없는지 검토  
- Tomcat 커넥션 및 비동기 요청 타임아웃 조정이 서비스 전반에 미치는 영향 점검
- [#10 공동구매 상품 관리 기능 개선 및 확장](https://github.com/100-hours-a-week/14-YG-BE/issues/10)
=> chore(config): WebClient, Tomcat 및 비동기 요청 타임아웃 120초로 연장

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyQueryController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/scheduler/GroupBuyScheduler.java
프론트엔드에서 커서 기반 페이지네이션을 구현하지 않은 점을 감안하여, 백엔드의 기본 조회 `limit` 값을 매우 큰 수로 상향 조정하고, 모집 마감 및 공구 종료를 처리하는 스케줄러를 매 정각(0분)과 30분에 실행되도록 수정했습니다.
- **기본 조회 `limit` 상향**  
- 공구 게시글 조회 API의 기본 `limit` 값을 `1_000_000`으로 설정  
- **스케줄러 cron 표현식 변경**  
- 모집 마감 스케줄러: `@Scheduled(cron = "0 0,30 * * * *")`  
- 공구 종료 스케줄러: `@Scheduled(cron = "0 0,30 * * * *")`  
- 기본 `limit` 상향이 네트워크 및 메모리에 과도한 부하를 주지 않는지 검토  
- 스케줄러 동시 실행 시 리소스 충돌 여부 및 성능 영향 점검  
- [#11 스케줄러 및 페이징 개선](https://github.com/100-hours-a-week/14-YG-BE/issues/11)
=> feat(group-buy): 기본 조회 limit 상향 및 모집, 종료 스케줄러 주기 수정

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java
주문 취소 시 해당 공동구매 글의 `dueSoon` 상태값을 즉시 반영하도록 수정
- 주문 취소 로직 수행 후 `groupBuy.updateDueSoonStatus(dueSoonPolicy);` 호출 추가  
- `dueSoonPolicy`를 활용해 남은 수량 기반으로 `dueSoon` 플래그 재계산  
- 응답 DTO나 매퍼 변경 없이 내부 상태만 갱신
- `./gradlew clean build` 및 `bootRun` 으로 애플리케이션 정상 기동 확인  
- Postman으로 주문 취소 API 호출 후  
- 응답에서 `data.posts[].dueSoon` 값이 변경된 것 확인  
- 관리 콘솔 또는 직접 조회 API 호출 시 즉시 반영된 상태 확인
- [#10 공동구매 상품 관리 기능 개선 및 확장](https://github.com/100-hours-a-week/14-YG-BE/issues/10)
=> fix(group-buy): 주문 취소 후 dueSoon 필드 값에도 상태 변경 반영 (#10)

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/client/AiClient.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyCommandController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java, src/main/java/com/moogsan/moongsan_backend/global/util/CookieUtils.java
사용자의 세션 쿠키(HTTP Only)를 외부 AI 서버 요청 시 WebClient에 포함하도록 수정했습니다.  
AI 서버가 인증된 사용자만 요청할 수 있도록 하기 위한 처리입니다.
- Controller에서 HttpServletRequest를 통해 `SESSION` 쿠키 추출  
- `groupBuyService.generate()` 및 `AiClient.generateDescription()` 메서드에 `sessionId` 파라미터 추가  
- WebClient 요청 시 `.cookie("SESSION", sessionId)`로 AI 서버에 전달  
- `CookieUtils` 유틸 클래스 추가하여 쿠키 추출 로직 재사용 가능하도록 분리
- 로컬 환경에서 `./gradlew clean build` 및 `bootRun` 실행 후 정상 기동 확인
- [#10 공동구매 상품 관리 기능 개선 및 확장](https://github.com/100-hours-a-week/14-YG-BE/issues/10)
=> feat(group-buy): 공구 설명 생성 시 사용자 세션 쿠키를 AI 요청에 포함

src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
403으로 나오던 401이 401로 정상 출력 하도록 수정하였습니다
- 403으로 나오던 401이 401로 정상 출력 하도록 securityConfig에서 변경
- build, bootrun, postman 확인 완료
- (#8)
=> fix(security): 401 상황 시, 401 정상 출력하게 수정

src/main/java/com/moogsan/moongsan_backend/domain/chatting/repository/ChatRoomRepository.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/HostedList/HostedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/ParticipatedList/ParticipatedListResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyHostedList.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyParticipatedList.java
- 참여·주최 공구 리스트 조회 시 `participantChatRoomId`를 응답에 포함하도록 개선
- 한 번의 `IN` 조회로 모든 참가자용 채팅방을 가져와 효율적으로 매핑
---
1. **ChatRoom 조회 로직 개선**
- `chatRoomRepository.findByGroupBuy_IdInAndType(groupBuyIds, "PARTICIPANT")` 호출로 한 번에 모든 채팅방 조회
- 조회된 결과를 `(groupBuyId → chatRoomId)` 형태의 Map으로 변환
2. **Mapper 시그니처 확장**
- `toParticipatedListWishResponse(List<Order> orders, Map<Long, Boolean> wishMap, List<ChatRoom> chatRooms)`
- `toParticipatedListResponse(Order o, boolean isWish, Long participantChatRoomId)`
- 주최 공구용 `toHostedListWishResponse`, `toHostedListResponse`도 동일하게 확장
3. **DTO 필드 추가**
- `ParticipatedListResponse`와 `HostedListResponse`에 `participantChatRoomId: Long` 필드 추가
4. **서비스 레이어 수정**
- `GetGroupBuyParticipatedList` 및 `GetGroupBuyHostedList`에서  
1) `List<GroupBuy>` → `groupBuyIds` 추출  
2) …
=> feat(group-buy): 주최 및 참여 공구 리스트 response에 참여자 채팅방 아이디 추가

Dockerfile, build.gradle, src/main/java/com/moogsan/moongsan_backend/domain/user/component/KakaoOAuthClient.java, src/main/java/com/moogsan/moongsan_backend/domain/user/controller/OAuthController.java, src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UserController.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/SignUpRequest.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/response/KakaoTokenResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/response/KakaoUserInfoResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/response/LoginResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/user/dto/response/OAuthSignUpInfoResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/user/entity/OAuth.java, src/main/java/com/moogsan/moongsan_backend/domain/user/exception/code/UserErrorCode.java, src/main/java/com/moogsan/moongsan_backend/domain/user/mapper/BankCodeMapper.java, src/main/java/com/moogsan/moongsan_backend/domain/user/repository/OAuthRepository.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/KakaoOAuthService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/LoginService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/SignUpService.java, src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java, src/main/resources/application.properties, src/main/resources/db/migration/V9__add_oauth_schema.sql
Kakao OAuth 추가 및 기존 로컬 계정과 연동 로직 설계, 계좌조회 시 은행코드 매핑 추가
- Kakao OAuth 작동 추가
- OAuth 추가로 인한 비밀번호 제한 변경
- OAuth를 통한 연동 로직 추가 (연동 기준은 이메일을 기준으로 연동)
- Kakao 로그인 시, 회원가입이 안되어 있으면, 이메일과 더미비밀번호를 프론트에 전달, 회원가입 유도
- Kakao 로그인 시, 연동이 되어있지 않는 동일 이메일의 로컬 정보가 있으면 자동 연동, Kakao 로그인 가능
- Kakao 로그인 시, 토큰 발급 및 기존의 로그인 흐름을 그대로 가져감
- 계좌인증 시, 한글 은행 명 입력 받아 숫자 코드로 변환 매핑 "[은행코드](https://www.notion.so/1fbabfbf55db8085ac68fa9bd70c0716)"
- 테스트나 실행 시, env에 추가할 항목
```
export OAUTH_KAKAO_CLIENT_ID=6317f0b1ed13c2f34f60fe743b3b79bc
export OAUTH_KAKAO_REDIRECT_URI=http://localhost:8080/api/oauth/kakao/callback
```
```
export OAUTH_KAKAO_CLIENT_ID=6317f0b1ed13c2f34f60fe743b3b79bc
export OAUTH_KAKAO_REDIRECT_URI=https://moongsan.com/api/oauth/kakao/callback
```
- Kakao 로그인 Redirect URL
- 아래의 URL을 버튼으로 연결해주시면 될 것 같습니다.
- …
=> feat(user): Kakao OAuth 추가

src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacade.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacadeImpl.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetLatestMessagesSseController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/CreateChatMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessageSse.java
- 기존 DeferredResult 기반 롱폴링 이외에 SseEmitter 기반 SSE를 추가했습니다. 다만 프론트엔드의 작업을 위해 현재 시점에서의 기본 방식은 롱 폴링으로 그대로 유지됩니다.
---
1. **SSE 서비스 로직 추가**  
- `GetLatestMessageSse` 클래스에 `SseEmitter` 생성·등록 및 제거 로직 구현  
- `notifyNewMessage`에서 `SseEmitter.event()`로 `"new-message"` 이벤트 푸시  
2. **롱폴링 관련 코드 유지**  
- DeferredResult 기반 메서드 및 관련 콜백 유지  
- `GetLatestMessages` 서비스의 롱폴링 전용 코드 유지
3. **보안 컨텍스트 전파 보장**  
- `DelegatingSecurityContextRunnable` 적용하여 Spring SecurityContext를 가상 스레드에서도 안전하게 유지  
4. **컨트롤러 매핑 수정**  
- `/api/chats/participant/{chatRoomId}/sse/latest` 엔드포인트로 SSE 연결  
- `ChattingQueryFacade#getLatestMessagesSse` 호출하도록 추가  
---
- **SSE 연결 테스트**  
- 클라이언트에서 `new EventSource("/api/chats/participant/{chatRoomId}/sse/latest")` 생성 후  
`"new-message"` 이벤트 정상 수신 확인  
- **SecurityContext 유지 확인**  
- 메시지 전송 시 …
=> feat(chatting): 롱폴링 기반 유지, SSE 도입

src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderCreateService.java, src/main/java/com/moogsan/moongsan_backend/domain/user/service/LoginService.java, src/test/java/com/moogsan/moongsan_backend/unit/order/service/OrderCreateServiceTest.java
feat(order): "주문 생성 시, 채팅방 참여"
- 카카오 로그아웃 테스트 완료 -> 기존 로그아웃과 로직 일치, 변경 없음
- 주문 생성 시, 채팅방 참여
- 로그인 시 deleted_at 기록하던 부분 삭제
- build, 실행 확인
- postman 실행 확인
- 주문을 생성한 참여자가 db상으로 해당 채팅방에 참여되어 있는 것을 확인
- #107
=> feat(order): "주문 생성 시, 채팅방 참여"

src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacade.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacadeImpl.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetLatestMessagesController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetLatestMessagesSseController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/CreateChatMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/JoinChatRoom.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessageSse.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java, src/main/java/com/moogsan/moongsan_backend/global/config/ConditionalOsivFilter.java, src/main/resources/application.properties
- **DB 커넥션 수명 최소화**를 위해 **SSE·롱폴링 엔드포인트에서만 OSIV(Open-Session-In-View) 비활성화**  
- OSIV 제거 과정에서 발생한 **`401 Unauthorized` 문제**를 별도 필터로 해결  
- **부하 테스트** 결과를 반영해 **DeferredResult·SseEmitter 처리 스레드를 JDK 21 Virtual Thread**로 전환  
- **HikariCP 누수 감지**를 위해 `spring.datasource.hikari.leak-detection-threshold=5000` 추가  
---
1. **OSIV 필터 개선**  
- `OsivExclusionFilter`(커스텀 `OncePerRequestFilter`) 추가  
- `/api/chats/**/latest` 경로에서만 `OpenSessionInViewFilter`를 건너뛰도록 구현  
- `shouldNotFilter` 로직 분리로 인증 필터 체인은 그대로 유지 → 401 문제 해결  
2. **Virtual Thread 적용**  
- `spring.threads.virtual.enabled=true` 설정  
- `Executors.newVirtualThreadPerTaskExecutor()` 기반으로  
- **DeferredResult** 롱폴링 콜백  
- **SseEmitter** 비동기 이벤트 전송 로직 실행  
3. **SSE 서비스 로직 추가**  
- `GetLatestMessageSse` 서비스 클래스  
- `SseEmitter` 등록·제거 및 …
=> feat(chatting): SSE·롱폴링 가상 스레드 전환 및 OSIV 필터 개선

src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacade.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacadeImpl.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetLatestMessagesController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetLatestMessagesSseController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/CreateChatMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/JoinChatRoom.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessageSse.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyListByCursor.java, src/main/java/com/moogsan/moongsan_backend/global/config/ConditionalOsivFilter.java, src/main/resources/application.properties
커서 기반 그룹 구매 목록 API에서 `PagedResponse.count` 필드에 사용되던 `result.getSize()`는  
**현재 페이지의 항목 수**만을 의미하고 있어, 실제 전체 개수와는 차이가 있었습니다.
이번 작업에서는 해당 필드를 **전체 조건에 부합하는 데이터 개수**로 명확하게 정의하기 위해  
`result.getTotalElements()`로 변경하였습니다.
---
1. **count 계산 방식 변경**
- 기존: `count(result.getSize())`  
→ 현재 페이지의 item 수 (ex. limit이 10이면 항상 10)
- 변경: `count(result.getTotalElements())`  
→ 조건에 맞는 전체 group buy 게시글 수 반환
2. **응답 의미 명확화**
- 프론트에서 페이지네이션 UI 구성 시 총 개수 기반으로 총 페이지 수 계산 가능
3. **일부 코드 변경**
- 부하 테스트 중 롱폴링(일반, 버추얼 플랫폼), SSE(일반, 버추얼 플랫폼) 검증에 필요한 일부 코드를 변경하였습니다
---
- 다양한 조건 (`keyword`, `categoryId`, `openOnly`, etc.) 조합으로 요청 후 `count` 정확성 확인
- 프론트에서 `posts.length`, `count`, `hasMore`의 불일치 여부 확인
- 테스트 케이스에서 반환된 `count` 값이 실제 DB 조건 필터링과 일치하는지 검증
---
---
- [#32 공동구매 기능 리팩토링 및 보안 …
=>  feat(group-buy): 그룹구매 목록 응답 count 필드 명확화

config/application-secrets.yml, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyUpdate/GroupBuyForUpdateResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/controller/query/GetGroupBuyHostAccountInfoTest.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/controller/query/GetGroupBuyHostedListTest.java
- `GroupBuy` 업데이트 URL 리턴 기능 추가 및 MockMvc 설정 보완
- 드라이버 이름 입력 방식을 변수 전달에서 직접 입력으로 분기 처리
---
1. update groupbuy API 호출 후 반환된 URL 리턴 기능 구현
2. @AutoConfigureMockMvc` 어노테이션 추가하여 컨트롤러 테스트 설정 보완  
3. 드라이버 이름 입력을 변수 파라미터 대신 Interactive Prompt로 전환  
---
---
- 모든 테스트가 성공했는지 (`./gradlew clean test`)  
- Postman 스크린샷 첨부 및 주요 API 응답 코드/내용 검토  
- `@AutoConfigureMockMvc` 적용으로 MockMvc 테스트가 정상 수행되는지 점검  
- 드라이버 이름 입력 로직 분기 처리 정상 동작 여부 확인  
---
- [#32 공동구매 기능 리팩토링 및 보안 개선](https://github.com/100-hours-a-week/14-YG-BE/issues/32)
=> GroupBuy 업데이트용 조회 시 URL 추가 반환 및 MockMvc 설정 보완

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/CreateGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/EndGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/LeaveGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/UpdateGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/global/config/TimeConfig.java, src/main/resources/db/migration/V10__rename_pickup_change_reason.sql, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/CreateGroupBuyTest.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/DeleteGroupBuyTest.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/EndGroupBuyTest.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/LeaveGroupBuyTest.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/UpdateGroupBuyTest.java
- 공구글 테스트 코드의 시간 관련 로직을 안정적으로 테스트할 수 있도록 `Clock`을 도입하고, 테스트 환경에서만 고정된 시간을 사용할 수 있도록 설정했습니다.
- 또한 가독성을 높이기 위해 `pickup_change_reason` 컬럼명을 `date_modification_reason`으로 수정했습니다.
- 각 테스트 케이스에 `@BeforeEach` 및 `times(n)` 기반의 호출 검증을 명시하여 테스트 신뢰도를 높였습니다.
---
1. **고정 시간 사용을 위한 환경 구성**
- `Clock` 및 `TestClockConfig` 생성
- 테스트 코드에서 `Clock.fixed()`를 활용해 시간 관련 테스트를 안정화
2. **DB 컬럼명 수정**
- `group_buy.pickup_change_reason` → `date_modification_reason`으로 변경 (Flyway V10 적용)
3. **테스트 리팩토링**
- `@BeforeEach`를 활용해 테스트마다 공통 세팅 적용
- `verify(..., times(n))` 및 `verify(..., never())` 등 명시적 호출 검증 추가
---
- 모든 관련 테스트가 고정 시간 기준으로 일관된 결과를 반환하는지 확인
- Flyway 마이그레이션이 정상적으로 동작하는지 확인 (`V10__rename_column.sql`)
- 실패 케이스에서 `verify(..., never())`가 적절히 적용되었는지 확인
---
---
- [[Sub Task] BE - 서비스단에서 times(n)을 통한 호출 여부 검증 …
=> test(group-buy): 고정 시간 적용, 호출 여부 검증

src/main/java/com/moogsan/moongsan_backend/domain/chatting/exception/specific/AlreadyJoinedException.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/exception/specific/ChatRoomInvalidStateException.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/exception/specific/ChatRoomNotFoundException.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/exception/specific/NotParticipantException.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/message/ResponseMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/CreateChatMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/JoinChatRoom.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/LeaveChatRoom.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetChatRoomList.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessageSse.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/command/CreateChatMessageTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/command/JoinChatRoomTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/command/LeaveChatRoomTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/query/GetChatRoomListTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/query/GetLatestMessagesSseTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/query/GetLatestMessagesTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/controller/query/GetPastMessagesTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/command/CreateChatMessageTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/command/JoinChatRoomTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/command/LeaveChatRoomTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/query/GetChatRoomListTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/query/GetLatestMessagesSseTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/query/GetLatestMessagesTest.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/query/GetPastMessagesTest.java
- 채팅 서비스 커맨드 및 쿼리 로직에 대한 단위 테스트 작성  
- `CreateChatMessage`, `JoinChatRoom`, `LeaveChatRoom` 커맨드 서비스 유닛 테스트  
- `GetChatRoomList`, `GetLatestMessages`, `GetLatestMessageSse` 쿼리 서비스 유닛 테스트  
- 고정 `Clock` 주입 검증 및 예외 시나리오 검증  
- 모든 테스트 클래스(`CreateChatMessageTest`, `JoinChatRoomTest`, `LeaveChatRoomTest`, `GetChatRoomListTest`, `GetLatestMessagesTest`, `GetLatestMessageSseTest`) 작성 완료 및 통과 확인  
---
- **커맨드 서비스 테스트**  
- `CreateChatMessageTest`  
- 채팅방 존재 여부, 삭제 여부, 참여자 여부 예외 검증  
- 메시지 시퀀스 생성, Redis ZSET 캐싱 동작 검증  
- `JoinChatRoomTest`  
- 주최자/참가자 정상 참여 경로 테스트  
- 공구 미존재, 미참여, 중복 참여 예외 검증  
- `LeaveChatRoomTest`  
- 참여자 정상 나가기 경로 테스트  
- 미참여, 채팅방 미존재, 비참여 예외 검증  
- **쿼리 서비스 테스트**  
- `GetChatRoomListTest`  
- 커서 기반 페이징(limit+1, nextCursor, hasMore) 정상 및 빈 결과 검증  
- `GetLatestMessagesTest`  
- …
=> test(chatting): 채팅 서비스 테스트 코드 작성

src/main/java/com/moogsan/moongsan_backend/domain/chatting/Facade/query/ChattingQueryFacadeImpl.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/repository/GroupBuyRepository.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/scheduler/GroupBuyScheduler.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/EndPastPickupGroupBuys.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyListByCursor.java, src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/query/GetLatestMessagesTest.java, src/test/resources/application-test.yml
**채팅 Long-Polling** 연결, 공구 목록 커서 페이징, 자동 마감 스케줄러, 테스트 프로파일의 버그를 수정했습니다.
* **Long-Polling** ― _한 유저당 1개의 요청 대기 큐_ 만 유지해 중복 응답 제거  
* **공구 전체 리스트 API** ― 커서 비교 연산을 `>`(GREATER) 로 교체하고 중복 ROW 방지  
* **자동 공구 마감** ― `<= now` 조건으로 경계값 누락 해결  
* **application-test.yml** ― 누락된 더미 OAuth 프로퍼티 추가 후 테스트 복구  
---
| # | 모듈 | 변경 사항 |
|:-:|------|-----------|
| **1** | **채팅 Long-Polling** | • `userId` 당 **BlockingQueue** 1개만 유지하도록 Registry 리팩터링<br>• 중복 큐 생성 시 기존 큐 반환 → “요청 1, 응답 1” 보장 |
| **2** | **채팅 테스트** | • 동일 `userId` 로 두 번 Polling 시 한 요청만 메시지 수신, 다른 요청은 타임아웃 확인 |
| **3** | **공구 목록 API** | • `Specification.where(distinct())` 적용<br>• 커서 조건 **`<` → `>`** 로 변경(가격·생성일·ID) |
| **4** | **자동 공구 마감** | • `dueDate <= now` 로 수정해 마감 시점 포함 |
| **5** | **테스트 프로파일** | • `application-test.yml` 에 더미 Kakao OAuth 키 …
=> fix(group-buy, chatting, test.yaml): 롱폴링 중복 응답, 공구 커서 누락, 마감 스케줄러, test.yml 오류 수정

build.gradle, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/query/GroupBuyListController.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyList/PagedResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/GroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/facade/query/GroupBuyQueryFacade.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/facade/query/GroupBuyQueryFacadeImpl.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/CreateGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyListByCursor.java, src/main/resources/application.properties, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/controller/query/GetGroupBuyListByCursorTest.java
1. **마감임박순 중복 제거**  
- 동일 `soldRatio` 내에서 페이지네이션 시 중복 아이템이 반환되는 문제 해결  
- 커서 페이징에 `cursorSoldRatio` 파라미터 추가  
2. **주문 즉시 마감임박 검사**  
- 주문(참여) 직후 `soldRatio`를 계산해 80% 이상 시 `postStatus`를 “CLOSED”로 변경  
3. **모니터링용 Spring Boot Actuator 추가**  
- ‘spring-boot-starter-actuator’ 의존성 추가  
- actuator 엔드포인트(health, metrics 등) 전부 노출 설정  
1. **GetGroupBuyListByCursor**  
- 메서드 시그니처에 `Integer cursorSoldRatio` 파라미터 추가  
- `Sort` 설정: `ending_soon` 모드에서 `soldRatio DESC, id ASC` 적용  
- `cursorSpec` 업데이트:  
- `ending_soon` 분기에서 `cb.lessThan(ratio, cursorSoldRatio)` 및 동률 시 `id` 비교 로직 추가  
- `PagedResponse` DTO에 `nextCursorSoldRatio` 필드 추가 및 빌더 반영  
2. **Controller API**  
- `/api/group-buys` GET 요청에 `cursorSoldRatio` RequestParam 추가  
3. **CreateGroupBuy Service**  
- 주문 처리 흐름에 …
=> feat(groupbuy): 마감임박순 페이징 중복 제거 및 주문 즉시 마감 반영, 액추에이터 추가

src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/CreateChatMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetPastMessages.java
- **작성자 본인이 작성한 메시지를 롱폴링을 통해 다시 수신하는 문제를 해결**
- **메시지 저장 직후 바로 알림을 전송하여 실시간성이 떨어진다는 체감 문제 개선**
- 궁극적으로는 SSE 또는 WebSocket으로의 전환이 필요하다고 판단되나,  
우선 현 롱폴링 구조에서 최대한 반응성을 끌어올리는 조치를 적용
---
1. **작성자 메시지 롱폴링 제외**
- `notifyNewMessage()` 내부에서 메시지 작성자의 `participantId`와 리스너의 `participantId`를 비교하여,
작성자 본인에게는 알림을 보내지 않도록 조건 분기 추가
2. **알림 호출 시점 개선**
- 기존에는 Redis 캐싱 이후에 `notifyNewMessage()`를 호출했으나, 메시지 저장 직후로 알림 호출 위치를 **선행 배치**
- Redis 캐싱은 실패해도 사용자 경험에 영향을 주지 않도록 뒤에서 처리
---
- 채팅 메시지 전송 시, 작성자 본인은 한 번만 메시지를 확인함 (낙관적 렌더링 or POST 응답 기반)
- 타 참여자는 롱폴링을 통해 실시간으로 새 메시지를 수신함
- Redis 캐싱 실패 시에도 메시지 실시간 전송에는 영향 없음
---
- Relates to **BE - v2 사전 배포 및 QA 진행 (#126)**
=> fix(chatting): 작성자 본인 메시지 중복 수신 제거 및 실시간 반응 속도 개선

src/main/java/com/moogsan/moongsan_backend/domain/chatting/controller/query/GetPastMessagesController.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/dto/query/ChatMessagePageResponse.java, src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetPastMessages.java
- 채팅 메시지 조회 시, 기존에는 **과거 → 최신** 순으로 응답하던 구조를
- **최신 → 과거** 순으로 조회하도록 방향성 전면 수정
- 가장 최근 메시지 기준으로 커서 페이징하여 **위로 스크롤 시 더 과거 메시지를 가져오는 구조**로 변경
- 또한, MongoDB 정렬 조건에서 필드 누락으로 발생하던 `Sort.by()` 런타임 예외를 수정
---
- 기본 조회 시 커서가 없으면 `Double.MAX_VALUE`부터 시작하여 최신 메시지 기준 조회
- Redis 조회 방식: `reverseRangeByScore()`를 항상 사용하여 최신 → 과거 순 정렬
- MongoDB 조회 시 정렬을 항상 `Sort.by(Sort.Direction.DESC, "_id")`로 통일
- 기존 `Sort.by(Sort.Direction.DESC)` → `IllegalArgumentException` 발생
- `_id` 필드를 명시하여 예외 방지
- 커서 기준 Mongo 조건: `_id < cursor` 로 설정하여 더 과거 메시지 조회
- 최종 응답도 `DESC` 정렬된 그대로 반환 (정렬 역전 없음)
- `Collections.reverse()` 제거
---
- 채팅방 진입 시 가장 최신 메시지가 리스트 상단에 위치하는지 확인
- 위로 스크롤할수록 이전(과거) 메시지가 정상적으로 로딩되는지 확인
- 메시지 순서가 **최신 → 과거**로 일관성 있게 내려오는지 확인
- 커서 기반 조회 시 중복 없이 정확히 이어지는지 확인
- 기존 `500 Internal Server Error` (`Sort.by()` 예외) …
=> fix(chatting): 최신 메세지부터 조회하도록 정렬 방향 수정 및 Mongo 정렬 예외 처리

src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyQueryService/GetGroupBuyListByCursor.java
`ending_soon` 정렬 시 커서 기반 페이지네이션에서 동일한 항목이 반복 응답되는 문제를 해결했습니다.  
정렬 기준(`soldRatio DESC, id ASC`)과 커서 조건이 불일치하여 중복된 응답이 발생하고 있었습니다.
---
- `cursorSpec()` 내 `"ending_soon"` 조건 로직 수정
- **Before**
```java
cb.or(
cb.lessThan(ratio, cursorSoldRatio),
cb.and(cb.equal(ratio, cursorSoldRatio), cb.lessThan(id, cursorId)),
cb.lessThan(id, cursorId)
)
```
- **After**
```java
cb.or(
cb.lessThan(ratio, cursorSoldRatio),
cb.and(cb.equal(ratio, cursorSoldRatio), cb.greaterThan(id, cursorId))
)
```
- `id` 오름차순 정렬 기준에 맞춰 `cb.greaterThan(id, cursorId)`로 수정
- 불필요한 조건 `cb.lessThan(id, cursorId)` 제거
---
- 동일 커서 요청 시, 같은 `postId`가 다시 포함되지 않음을 확인
- 프론트엔드 무한 스크롤에서 중복 아이템 제거 없이도 정상 동작하는지 확인
- 로그 또는 응답값 기준 `nextCursorId`, `nextSoldRatio` 정상 이동 여부 확인
---
---
- Relates to **BE - v2 사전 배포 및 QA 진행 (#126)**
=> fix(group_buy): ending_soon 정렬 기준에서 커서 기반 페이징 중복 응답 문제 해결

build.gradle, docker-compose.yml, src/main/java/com/moogsan/moongsan_backend/domain/notification/controller/KafkaTestController.java, src/main/java/com/moogsan/moongsan_backend/domain/notification/dto/SimpleMessage.java, src/main/java/com/moogsan/moongsan_backend/domain/notification/service/KafkaMessageListener.java, src/main/java/com/moogsan/moongsan_backend/global/config/KafkaConfig.java, src/main/java/com/moogsan/moongsan_backend/global/outbox/OutboxEventEntity.java, src/main/java/com/moogsan/moongsan_backend/global/outbox/OutboxEventStatus.java, src/main/java/com/moogsan/moongsan_backend/global/outbox/OutboxWorker.java, src/main/resources/application.properties, src/main/resources/db/migration/V11__create_outbox_event_table.sql, src/main/resources/logback-spring.xml
- Kafka를 벤치마킹한 후 **초기 Zookeeper 3대 고정** 설정을 완료했습니다.  
- Docker Compose와 Dockerfile을 작성해 **Kafka–Zookeeper–앱** 스택을 로컬/데브 환경에서 부트스트랩했습니다.  
- Spring Boot 애플리케이션에 **Kafka Producer/Consumer** 코드를 추가해 메시지 전송과 응답을 동기 방식으로 확인했습니다.  
- application.properties만으로는 제어되지 않던 **Kafka 내부 DEBUG/INFO 로그**를 `logback-spring.xml`로 레벨 조정해 깔끔하게 출력되도록 개선했습니다.  
- Outbox 패턴 도입을 위해 **OutboxEvent 테이블(V11 마이그레이션)** 과 **OutboxWorker** 초안을 준비했습니다.  
---
1. **Zookeeper & Kafka 클러스터 구성**  
- Zookeeper 3대, Kafka 브로커 3대를 Docker Compose로 고정했습니다.  
- 개발 단계에서는 각 토픽의 복제 팩터(RF)를 1로 설정했고, 프로덕션 환경에서는 RF≥2를 허용하도록 추가 구현이 필요함을 명시했습니다.  
2. **Docker 환경 설정**  
- `docker-compose.yml`과 `Dockerfile`에 Zookeeper, Kafka, Redis, Backend 컨테이너를 정의했습니다.  
- 각 서비스의 볼륨을 분리해 데이터 영속화를 구현했으나, 볼륨 삭제 시 토픽이 함께 삭제되는 문제를 후속 과제로 남겼습니다.  
3. **Spring …
=> feat(Kafka): Kafka 도입 및 로그 최적화, Outbox 패턴 준비

src/main/java/com/moogsan/moongsan_backend/adapters/kafka/listener/ChatNotificationListener.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/listener/GroupBuyNotificationListener.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/listener/OrderNotificationListener.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/producer/dto/OrderCanceledEvent.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/producer/dto/OrderConfirmedEvent.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/producer/dto/OrderRefundedEvent.java, src/main/java/com/moogsan/moongsan_backend/adapters/kafka/producer/mapper/OrderEventMapper.java, src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/LeaveGroupBuy.java, src/main/java/com/moogsan/moongsan_backend/domain/notification/entity/NotificationType.java, src/main/java/com/moogsan/moongsan_backend/domain/notification/service/SendOrderNotificationUseCase.java, src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderStatusUpdateService.java, src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/LeaveGroupBuyTest.java
- **Notification 서브도메인** 초판 도입 → Kafka Consumer → SSE Push 파이프라인 구축  
- **Order 이벤트 컨슈머**(대기‧확정‧취소‧환불) 로직 적용  
- **실시간 알림 인프라 구성**  
- `SseEmitterRepository`, `NotificationType`, `NotificationTemplateRegistry` 신규 도입  
- **주문 End-to-End 테스트** 구현 (#265)  
- Kafka Listener 컨테이너팩토리 & JSON Deserializer 설정 리팩터링  
---
| 범주 | 변경 내역 |
| ---- | -------- |
| **Kafka Consumer** | `KafkaNotificationListener` 추가<br>  • `ORDER_STATUS_PENDING` 수신 & manual ack<br>  • `ConsumerGroups.NOTIFICATION` 상수 정의 |
| **Notification** | `NotificationType` enum / `NotificationTemplateRegistry` 신설<br>`SendOrderNotificationUseCase` → 호스트 대상 알림 전송<br>`SseEmitterRepository` (동시성 안전) & `/api/sse/notifications` 컨트롤러 |
| **DTO** | `OrderPendingEvent` 필드 확장 (`hostId`, `buyerName`, `quantity`) |
| **Config** | `KafkaConfig` → …
=> feat(notification): 주문 컨슈머, SSE 알림 파이프라인 구축 및 주문 E2E 테스트 완료
