100-hours-a-week/14-YG-BE

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UserController.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/LogoutService.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/SignUpService.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/WithdrawService.java
로그아웃/회원탈퇴/회원가입 자동 로그인
- 로그아웃이 토큰을 제거합니다
- 회원탈퇴가 토큰을 제거합니다
- 회원가입이 토큰과 회원정보를 등록, 토큰 테이블에 토큰을 등록합니다
- 일부 예외 처리 작성
- 테스트 완료
> feat(user): 로그아웃/회원탈퇴/회원가입 자동 로그인

- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyCommandController.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/controller/GroupBuyQueryController.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/entity/GroupBuy.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyCommandMapper.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/repository/OrderRepository.java
V1 작업 마무리 및 V2 준비
- 작업 시 적어두었던 주석 및 코드 제거
- 공구 게시글 생성 시 주문 단위 관련 검증 로직 추가
- 공구 게시글 수정, 삭제 controller와 service 코드 추가
-
- 
- [[Sprint #3] BE - 공동구매 상품 관리 기능 개발](https://github.com/100-hours-a-week/14-YG-BE/issues/9)
> chore(groupbuy): 사용하지 않는 코드 제거, V2 작업 시작

- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/query/response/groupBuyDetail/UserProfileResponse.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/mapper/GroupBuyQueryMapper.java
- src/main/java/com/moogsan/moongsan_backend/domain/image/service/FileService.java
> chore(group-buy): 유저 정보 조회 컬럼 수정, s3 저장 경로 수정

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UserController.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/WishRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/entity/Wish.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/repository/WishRepository.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/WishService.java
- src/main/resources/application.properties
feat(user): Wish 추가
Wish를 User에서 만들었습니다.
- Wish entity, dto, controller, service 추가
- Wish POST/DELETE 추가
- build, bootrun, postman 확인 완료
- https://github.com/orgs/100-hours-a-week/projects/144/views/1?pane=issue&itemId=109609721&issue=100-hours-a-week%7C14-YG-BE%7C53
> feat(user): Wish 추가

- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/response/DescriptionDto.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService.java
> fix(group-buy): bug fix cancel order completed

- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/client/AiClient.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/response/DescriptionDto.java
> feat(group-buy): change ApiResponse mapping

- src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
securityconfig permitAll 설정에 /api/users/check-email 추가
- securityconfig permitAll 설정에 /api/users/check-email 추가
- build/bootRun 확인
- postman 확인
> feat(user): add check-email api at securityconfig, permitAll

- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/dto/command/response/DescriptionDto.java
ai 상품 상세 설명 생성 api에 맞춰 descriptionDto 수정
- 
-
- 
-
> feat(group-buy): update ai description dto (#10)

- src/main/java/com/moogsan/moongsan_backend/domain/order/controller/OrderController.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/dto/response/OrderCreateResponse.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderCreateService.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/exception/base/UserException.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/exception/handler/UserExceptionHandler.java
User 예외 응답 수정, Order 응답 추가
- User 예외 처리 응답이 code, message로 오던 것을 message, data로 수정
- Order의 응답을 프론트가 주문한 사항으로 변경
- build/bootRun 확인
- postman 확인
- https://github.com/orgs/100-hours-a-week/projects/144/views/1?pane=issue&itemId=108180104&issue=100-hours-a-week%7C14-YG-BE%7C8
> fix(user)/feat(order): User 예외 응답 수정, Order 응답 추가

- src/main/java/com/moogsan/moongsan_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/WithdrawService.java
회원탈퇴 조건 추가
- 회원탈퇴 조건 추가
- 회원 탈퇴는 order.status가 Confirmed/Canceled, group-buys.postStuatus가 ENDED일 때만 회원 탈퇴 가능
- build, boorRun, postman 확인 완료
- https://github.com/orgs/100-hours-a-week/projects/144/views/1?pane=issue&itemId=108180104&issue=100-hours-a-week%7C14-YG-BE%7C8
> fix(user, order): 회원탈퇴 조건 추가

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/UpdateProfileController.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/UpdateProfileAccountRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/UpdateProfileImageRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/UpdateProfilePasswordRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/dto/request/UpdateProfileRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/UpdateProfileService.java
- src/main/java/com/moogsan/moongsan_backend/global/exception/base/GlobalExceptionHandler.java
- src/test/java/com/moogsan/moongsan_backend/unit/user/controller/OAuthControllerTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/user/controller/UpdateProfileControllerTest.java
UpdateUserContoller, OAuthController Test 코드 작성
- UpdateUserControllerTest 코드 작성
- OAuthControllerTest 코드 작성
- 응답코드 500의 내용을 반영하기 위해 전역예외처리에 코드 추가
- ./gradlew build 확인 완료
- 실행 확인 완료
- postman 작동 확인 완료
- #92 
- #94 
- #95
> test(user, oauth): UpdateUserContoller, OAuthController Test 코드 작성

- src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/JoinChatRoom.java
- src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/command/LeaveChatRoom.java
- src/main/java/com/moogsan/moongsan_backend/domain/groupbuy/service/GroupBuyCommandService/LeaveGroupBuy.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/controller/OrderController.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/dto/request/OrderStatusUpdateRequest.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/dto/response/OrderCreateResponse.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/dto/response/OrderParticipantResponse.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/repository/OrderRepository.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderCreateService.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderQueryService.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderStatusUpdateService.java
- src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/command/JoinChatRoomTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/chatting/service/command/LeaveChatRoomTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/groupbuy/service/command/LeaveGroupBuyTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/order/controller/OrderControllerTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/order/service/OrderCreateServiceTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/user/controller/UpdateProfileControllerTest.java
공동구매 주문 참여자 조회 생성, UpdateProfileControllerTest 리펙토링,
주문 상태에 REFUNDED 상태 추가에 여러 코드 수정
- 공동구매 주문 참여자 조회 생성 - 모든 상태 조회
- 주문 상태 변경 로직 변경 - 리스트로 유저 상태를 한번에 변경, REFUNDED 상태 도입
- REFUNDED 상태 도입으로 인한 로직 변경 - REFUNDED는 상태만 추가됐을 뿐 큰 변경은 없음
- UpdateProfileControllerTest 리펙토링 - BeforeEach 반영
- ./gradlew build 통과
- 실행확인, postman 확인 완료
- REFUNDED 상태 도입으로 인해 코드 수정이 있습니다 확인해주세요
- JoinChatRoom
- LeaveChatRoom
- JoinChatRoomTest
- LeaveChatRoomTest 
- #107
> feat/fix/test(user, order): 공동구매 주문 참여자 조회 생성, 주문 로직 일부 변경 등

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/OAuthController.java
- src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
- src/main/resources/application.properties
- src/test/java/com/moogsan/moongsan_backend/unit/user/controller/OAuthControllerTest.java
- src/test/java/com/moogsan/moongsan_backend/unit/user/controller/UpdateProfileControllerTest.java
OAuth 로직 변경
- OAuth 로직 변경입니다
- 로컬 동작은 완료되었는데 프론트와 테스트를 해야합니다
- 로컬 빌드, 포스트맨 확인
- #92
> fix(OAuth): OAuth 로직 변경

- src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetPastMessages.java
- 기존에 잘 동작하던 커서 기반 양방향 페이징 로직(`isPrev`, `cursorScore`)이 다른 커밋으로 인해 덮어써졌습니다.
- 해당 로직을 복원하고 다시 반영합니다.
---
- `GetPastMessages` 서비스에서 `cursorMessageIdBefore`/`After` 분기 (`isPrev` 도입)
- Redis `rangeByScore` / `reverseRangeByScore` 분기 처리
- Mongo 정렬 방향 보정 + `Collections.reverse()`
- Controller, Facade 등에서 `isPrev` 계산 방식 반영
---
---
- 해당 PR은 실수로 덮어쓴 커밋을 되돌리는 "revert 목적" PR입니다.
- 관련 기능은 문제없이 작동했으나 실수로 유실되어 복구합니다.
> revert(chatting): 채팅 메시지 커서 기반 페이징 로직 복원

- src/main/java/com/moogsan/moongsan_backend/domain/order/repository/OrderRepository.java
참여자 조회 순서 변경
- 순서를 취소-입금전-입금확인-환불완료의 상태로 변경
- ./gradlew build, run, postman 확인 완료
- #107
> fix(order): 참여자 조회 순서 변경

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/OAuthController.java
500 에러의 정보를 확인하기 위해 log를 추가했습니다
- OAuthController에 log 추가
- ./gradlew build 확인 완료
- #92
> fix(OAuth): add log at OAuthController

- src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetLatestMessages.java
1. 롱폴링(`GetLatestMessages.notifyNewMessage`)에서 발신자 메시지 제외 조건 제거  
2. 모든 메시지(발신자 포함)를 실시간 스트리밍 API로 통일 제공  
3. 클라이언트에 메시지 중복 제거 및 타임스탬프 기반 정렬 책임 위임
---
- **`GetLatestMessages.notifyNewMessage`**
- 기존에 발신자와 동일한 `participantId` 경우 알림 제외하던 `continue` 로직 제거  
- **실시간 알림 호출 방식**
- `Thread.startVirtualThread(…)`을 통해 모든 구독자에게 즉시 알림 전송  
- **클라이언트 가이드**
- 메시지 합병 시 `messageId` 기준 중복 필터링 및 `createdAt` 순 오름차순 정렬 예시 추가 (문서화)
- **API 문서 업데이트**
- 실시간 스트리밍 엔드포인트 스펙에 ‘발신자 포함’ 사실 명시
---
1. **발신자 테스트**  
- 메시지 전송 후 발신자도 실시간 알림으로 동일 메시지 수신 확인  
2. **수신자 테스트**  
- 다른 사용자가 보낸 메시지도 정상 수신  
3. **순서·중복 테스트**  
- 클라이언트에서 합쳐진 메시지 리스트에 중복 없이, `createdAt` 순으로 정렬되어 렌더링되는지 확인  
4. **과거 조회 혼합 테스트**  
- cursor 기반 과거 메시지 조회 결과와 실시간 알림 메시지를 합쳤을 때 순서가 일관되게 유지되는지 검증
---
- 테스트 케이스에 발신자 포함 시나리오 추가  
- 클라이언트 샘플 앱에서 중복 제거·정렬 로직 …
> fix(chatting): 롱폴링 알림에서 발신자 제외 로직 제거 및 메시지 중복·정렬 처리 클라이언트 이관

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/OAuthController.java
url 입력 방식 수정
- 서비스 로그인에서 url과 code를 파라미터로 입력받아 사용하게 변경하였습니다
- build, 실행, postman 확인 완료
- #92
> fix(OAuth): url입력 방식 수정

- src/main/java/com/moogsan/moongsan_backend/domain/chatting/service/query/GetPastMessages.java
- 과거 채팅 메시지를 커서 기반으로 조회할 때, 커서 기준 메시지가 **목록의 첫 번째 요소로 설정**되어 이전 메시지들이 누락되거나 중복되는 문제 발생
- 커서 기준을 **마지막 요소로 수정**하여 커서 기반 페이지네이션의 방향성과 일치하도록 변경
---
- 과거 메시지 조회 시 커서를 설정할 때 `messages.get(0)` → `messages.get(messages.size() - 1)`로 변경
- 커서 페이징의 방향이 최신 → 과거 순임을 고려하여, 페이지의 **마지막 메시지 기준으로 커서 설정**
---
- 메시지 조회 API에서 페이지당 20개 메시지 요청 시, 응답의 마지막 메시지를 커서로 설정하고 다음 페이지 조회 시 이어지는 메시지가 정확히 반환되는지 확인
- 이전 커서 사용 방식으로 인한 중복/누락 여부 테스트
---
- 커서 기준이 `DESC` 정렬 방향성과 일치하는지 재검토
- 테스트 코드 내 커서 설정 방식도 동일하게 적용되었는지 확인
---
- Relates to **BE - v2 사전 배포 및 QA 진행 (#126)**
> fix(chat): 분기에 따른 beforeCursor 수정

- src/main/java/com/moogsan/moongsan_backend/domain/chatting_anon/controller/ChatAnonStompController.java
- src/main/java/com/moogsan/moongsan_backend/domain/chatting_anon/dto/ChatAnonDto.java
- src/main/java/com/moogsan/moongsan_backend/domain/chatting_anon/entity/ChatAnon.java
- src/main/java/com/moogsan/moongsan_backend/domain/chatting_anon/repository/ChatAnonRepository.java
- src/main/java/com/moogsan/moongsan_backend/domain/chatting_anon/service/sendChatAnonService.java
- src/main/java/com/moogsan/moongsan_backend/domain/order/service/OrderCreateService.java
- src/main/java/com/moogsan/moongsan_backend/global/config/SecurityConfig.java
- src/main/java/com/moogsan/moongsan_backend/global/config/WebSocketConfig.java
- src/main/resources/static/test-chat.html
- 익명 채팅방은 아직 웹소켓 단계에서 구현 중입니다.
- 오더 생성 내 순서를 변경하였습니다.
- domain 내 chatting_anon 파일 생성 후 작업 중
- global 내 WebSocketConfig 생성 후 작업 중
- SecurityConfig가 가독성이 좋지 않아 좀 정리했습니다
- ./gradlew build 확인
- #246 명
> feat(chatting_anon): 익명 채팅방 구조 구현 중, 오더 생성 순서 변경

- src/main/java/com/moogsan/moongsan_backend/domain/user/controller/OAuthController.java
- src/main/java/com/moogsan/moongsan_backend/domain/user/service/KakaoOAuthService.java
- src/test/java/com/moogsan/moongsan_backend/unit/user/service/KakaoOAuthServiceTest.java
OAuth 회원가입 응답 코드 수정
- OAuth 회원가입 응답 코드 수정
- postman 확인 완료
- 이슈없음
> fix(OAuth): OAuth 회원가입 응답 코드 수정
